name = "candle-timer"
main = "worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"

# Created once with `npx wrangler kv namespace create CANDLES`, then the id
# that command prints replaces the placeholder below. See DEPLOY.md.
[[kv_namespaces]]
binding = "CANDLES"
id = "b927147c8c8a4062a387730718c2c195"
